### ISSUE TITLE
NFR 2: Low failure rate

### ISSUE THREAD

**Issue by hyihua** [Croquembouche/pyWhat-2022#10]
|NFR Availability1: Low failure rate|
|----------------------|
| **Estimate:** 5|  
| **Priority:** Should have |
|**Story**: As a developer, I want the application to be 100% operational 99% of the calendar year so that every user can use this app at any time.|
| **Acceptance criteria:** |
|1.The app works fine.|
|2.In 1000 runs, the app fails to run no more than 2 times.|

**Comment by Croquembouche** [comment]
The application is tested using a loop and guarantees that it runs with low failure rate as identified in the NFR.
