### ISSUE TITLE
FR 7: Matching URLs

### ISSUE THREAD

**Issue by HamiedAsadi** [Croquembouche/pyWhat-2022#14]
Hamid Asadi
    |FR 7: URL |
|----------------------|
| **Estimate:** 21 |
| **Priority:** Should have |
|**Story**: As a developer, I want URL regex fully match every URL . So it to return both google.co and google.com|
| **Acceptance criteria:** |
|Match the longest string and return the result. (pywhat google.com/help should return google.com/help).|

<img width="506" alt="125897831-fa1f066e-d9b7-433c-9fc1-91365713c878" src="https://user-images.githubusercontent.com/94477661/196573681-2321c3a0-f61a-438d-b708-6d2dedc07c83.png">
>

**Comment by Croquembouche** [comment]
Issue closed due to pull request from original branch.
