### ISSUE TITLE
NFR13: Usability

### ISSUE THREAD

**Issue by ZichuanLiu20** [Croquembouche/pyWhat-2022#24]
|NFR 13: Usability|
|----------------------|
| **Estimate:** 5 |  
| **Priority:** Should have |
|**Story**: As a user, I want the GUI interface should be simple and easy to use so that I can save time.|
| **Acceptance criteria:** |
|1. GUI interface should be simple and easy to use.|
|2. The GUI interface should not be confusing.|

**Comment by Croquembouche** [comment]
The GUI is easy to use and does not have any confusing components.
