### ISSUE TITLE
FR 8: Query History

### ISSUE THREAD

**Issue by ZichuanLiu20** [Croquembouche/pyWhat-2022#26]
|FR 8: Query History|
|----------------------|
| *Estimate:* 5 |  
| *Priority:* Should have |
|*Story: As a user, I want to see my previous searches so I can save time and go straight to the results of my last search:* |
|1. The application can show query history .|

**Comment by Croquembouche** [comment]
I have finished implementing this...accidentally.

**Comment by qchiujunhao** [comment]
But Yihua and I also finished this last night on branch queryhistory.





On Wednesday, November 9, 2022, 10:19 AM, Yuankai(William) He ***@***.***> wrote:




I have finished implementing this...accidentally.

**Comment by Croquembouche** [comment]
OK. No problem. We can do a merge later on.
