### ISSUE TITLE
NFR 1: Multiple Users

### ISSUE THREAD

**Issue by hyihua** [Croquembouche/pyWhat-2022#8]
|NFR Performance1: Multiple Users |
|----------------------|
| **Estimate:** 5 |  
| **Priority:** Must have |
|**Story**: As a developer, I want pyWhat to be able to support multiple users to query simultaneously so that multiple users can use it at the same time.|
| **Acceptance criteria:** |
|1.The app correctly server requests from users.|
|2.The app works on different laptops.|

**Comment by Croquembouche** [comment]
NR closed because each user will have their own instances.
